name: antapp
description: "A new Flutter project."

publish_to: 'none' 


environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/  